const Texts = {
  novopedido: "Adicionar ao Carrinho",
  add: "Adicionar",
  additionals: "Adicionais",
  aberto_ate: "Aberto até as",
  carrinho: "Meu Pedido",
  item: "item",
  items: "items",
  inicio: "Início",
  subtotal: "Subtotal",
  finalizar_pagamento: "Finalizar Pedido",
  finalizando_pedido: "Finalizando Pedido...",
  resumo_valores: "Resumo de Valores",
  entrega: "Entrega",
  km: "km",
  salvar: "Salvar",
  voltar: "Voltar",
  fora_area_delivery: "Fora da área de entrega",
  total: "Total",
  fora_area: "Fora da área de entrega",
  alter: "Alterar",
  metodos_pagamentos: "Pagamento",
  todos: "Todos",
  telefone: "Telefone",
  endereco: "Endereço",
  credit: "Crédito",
  debit: "Débito",
  money: "Dinheiro",
  pix: "PIX",
  nome_es: "Nome",
  erroPedido: "Ouve um erro nao fazer o pedido, tente novamente.",
  calculando: "Calculando...",
  nenhum_estabelecimento_aberto: "Nenhum restaurante aberto no momento.",

  IN_ROUTE_COLECT: "À caminho da coleta",
  AWAIT_COLECT: "Aguardando Pedido",
  AWAIT_APPROVE: "Aguardando Aprovação",
  DONE: "Em Rota de entrega",
  IN_ROUTE_DELIVERY: "Em Rota de entrega",
  APPROVED: "Preparando seu pedido",
  FINISH: "Entregue",
  FINISHED: "Entregue",
  forma_pay: "Pagamento",
};
export default Texts;
