export default {
  IN_ROUTE_COLECT: "À caminho da coleta",
  AWAIT_COLECT: "Aguardando Pedido",
  IN_ROUTE_DELIVERY: "Em Rota de entrega",
  FINISH: "Entregue",
  FINISHED: "Entrgue",
  credit: "Crédito",
  debit: "Débito",
  pix: "PIX",
  money: "Dinheiro",
  forma_pay: "Forma de Pagamento",
  phone: "Telefone",
  entregador: "Entregador",
  status: "Status",
  itens_carrinho: "Itens no Carrinho",
  ocultar_itens: "Ocultar Itens",
  vizualizar_itens: "Visualizar Itens",
  cardapio_sucess: "Cardápio alterado com sucesso!",
  erro_cardapio: "Ocorreu um erro, por favor tente novamente.",
  editar_itens: "Editar Produto",
  description: "Descrição",
  cancelar: "Cancelar",
  salvar: "Salvar",
  imagem: "Imagem",
  establishment_open: "Seu estabelecimento foi aberto!",
  gestor_cardapio: "Gestor de Cardápio",
  meus_pedidos: "Meus Pedidos",
  email_end: "Endereço de e-mail",
  text_login: "Faça login na sua conta",
  categorias: "Categorias",
  password: "Senha",
  esqueceu_senha: "Esqueceu sua senha?",
  entrar: "Entrar",
  additional: "Adicionais",
};
