export default {
  IN_ROUTE_COLECT: "À caminho da coleta",
  AWAIT_COLECT: "Aguardando Pedido",
  IN_ROUTE_DELIVERY: "Em Rota de entrega",
  FINISH: "Entregue",
  FINISHED: "Entregue",
  credit: "Crédito",
  debit: "Débito",
  pix: "PIX",
  money: "Dinheiro",
  forma_pay: "Pagamento",
  phone: "Tel",
  entregador: "Entregador",
  nome: "Nome",
  status: "Status",
  preco: "Preço",
  acoes: "Ações",
  remover_produto: "Remover Produto",
  search_placeholer: "Buscar...",
  novo_produto: "Novo Produto",
  id: "ID",
  adicionar_no_produto: "Adicionar no Produto",
  adicionado_no_produto: "Alteração realizada com sucesso",
  restaurant_error:
    "Ouve um problema ao atualizar o estabelecimento, tente novamente.",
  itens_carrinho: "Itens no Carrinho",
  ocultar_itens: "Ocultar Itens",
  vizualizar_itens: "Visualizar Itens",
  salve_primeiro: "Por favor, salve o produto antes de fazer essa operação.",
  cardapio_sucess: "Cardápio alterado com sucesso!",
  erro_cardapio: "Ocorreu um problema, por favor tente novamente.",
  editar_itens: "Editar Produto",
  description: "Descrição",
  cancelar: "Cancelar",
  salvar: "Salvar",
  restaurant_update:
    "Os dados do estabelecimento foram atualizados com sucesso.",
  removido_produto: "Produto removido com sucesso!",
  falha_remover_produto: "Ouve um erro ao remover o produto, tente novamente.",
  imagem: "Imagem",
  establishment_open: "Seu estabelecimento foi aberto!",
  gestor_cardapio: "Gestor de Cardápio",
  meus_pedidos: "Meus Pedidos",
  email_end: "Endereço de e-mail",
  text_login: "Faça login na sua conta",
  categorias: "Categorias",
  password: "Senha",
  esqueceu_senha: "Esqueceu sua senha?",
  entrar: "Entrar",
  additional: "Adicionais",
  alteracao_aplicada: "Atualização aplicada.",
};
