import Strings from "./Strings";

const Texts = {
  coleta: "COLETA",
  disponivel: "Disponível",
  indisponivel: "Indisponível",
  notificacoes: "Notificações",
  perfil: "Perfil",
  maps: "Mapa",
  aceitar: "Aceitar",
  confirmar: "Confirmar",
  valorEntrega: "Valor da Entrega",
  establishment: "Estabelecimento",
  localizacao: "Localização",
  cliente: "Cliente",
  nome: "Nome",
  distancia: "Distância",
  data: "Data",
  km: "km",
  aceitar_entrega: "Aceitar Entrega",
  valor: "Valor",
  minutos: "min",
  pedido: "Pedido",
  compartilhar: "Compartilhar",
  aceitar_rota: "Aceitar a rota?",
  entrega: "Entrega",
  voltar: "Voltar",
  em_entrega: "Em Coleta",
  continue_duvida: "Você realmente deseja continuar?",
  nao_sera_possivel_voltar: "Não será possível voltar após confirmar",
  notfound_extract: "Nenhuma entrega encontrada",
  extract: "Detalhes da Entrega",
  ...Strings.status,
};

export default Texts;
